name: Auto-Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to S3
      run: |
        export AWS_ACCESS_KEY_ID="AKIAZMQB4RCOT6EYLWNA"
        export AWS_SECRET_ACCESS_KEY="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"
        export AWS_DEFAULT_REGION="us-east-1"
        aws s3 sync . s3://portfolio-manohar --delete --exclude ".git/*" --exclude ".github/*"

    - name: Invalidate CloudFront Cache
      run: |
        export AWS_ACCESS_KEY_ID="AKIAZMQB4RCOT6EYLWNA"
        export AWS_SECRET_ACCESS_KEY="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"
        export AWS_DEFAULT_REGION="us-east-1"
        aws cloudfront create-invalidation --distribution-id E2XLGKKG43XS6H --paths "/*"